### ISSUE TITLE
All webgl games will not run in file urls

### ISSUE THREAD

**Issue by YourSeriousDev** [metalfoxdev/gr1d#13]
All webgl games will need to be run off a webserver due to Cors restrictions

**Comment by metalfoxdev** [comment]
Normally, this is the case. But there is a workaround which I have used. I just use data: urls to embed every single data file and resource and it works. If I hadn't tested this before, gr1d would not have been offline oriented. Therefore, this is not an issue and I will close it now. (I will make a guide on how to do this soon)
